version: '3.8'

# Configuration simple pour pull depuis Docker Hub
# Usage: docker-compose -f docker-compose.demo.yml up -d

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - demo-db-data:/var/lib/postgresql/data

  odoo:
    # Image pré-construite sur Docker Hub
    image: virgile42d/odoo-souscription-demo:latest
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - demo-web-data:/var/lib/odoo

volumes:
  demo-db-data:
  demo-web-data: