version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 5s
      timeout: 5s
      retries: 5
    # Optimisations pour performances
    command: >
      postgres
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c work_mem=4MB
      -c max_connections=50

  odoo:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./:/mnt/extra-addons/souscriptions:ro
      - ./config/odoo-prod.conf:/etc/odoo/odoo.conf:ro
    # Limiter l'utilisation mémoire
    deploy:
      resources:
        limits:
          memory: 1500M
        reservations:
          memory: 1000M
    command: >
      odoo
      --db_host=db
      --db_user=odoo
      --db_password=odoo
      --addons-path=/usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
      --load-language=fr_FR

volumes:
  odoo-db-data:
  odoo-web-data: