version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 5s
      timeout: 5s
      retries: 5

  odoo:
    build: 
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ../:/mnt/extra-addons/souscriptions:ro
      - ./config/odoo.conf:/etc/odoo/odoo.conf:ro
    command: >
      odoo
      --db_host=db
      --db_user=odoo
      --db_password=odoo
      --addons-path=/usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
      --load-language=fr_FR

  odoo-dev:
    build: 
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8070:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ../:/mnt/extra-addons/souscriptions:rw
    command: >
      odoo
      --db_host=db
      --db_user=odoo
      --db_password=odoo
      --addons-path=/usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
      --load-language=fr_FR
      --dev=reload,xml,qweb
    profiles:
      - dev

volumes:
  odoo-db-data:
  odoo-web-data: